// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3_khmszw53YXkR7-BvME0srGFEYjnKzQ',
    appId: '1:90398917089:android:bd9725c6bef2d4aaff52a0',
    messagingSenderId: '90398917089',
    projectId: 'flutter-chat-app-1c812',
    storageBucket: 'flutter-chat-app-1c812.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmDywgQ9yZVCebkKcOCtuLIsW-GpiEBVs',
    appId: '1:90398917089:ios:c8e10c25d764b1efff52a0',
    messagingSenderId: '90398917089',
    projectId: 'flutter-chat-app-1c812',
    storageBucket: 'flutter-chat-app-1c812.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3-Ync6De41xYwtZtpZBLreoik1aJcqKY',
    appId: '1:90398917089:web:9a374da430d47558ff52a0',
    messagingSenderId: '90398917089',
    projectId: 'flutter-chat-app-1c812',
    authDomain: 'flutter-chat-app-1c812.firebaseapp.com',
    storageBucket: 'flutter-chat-app-1c812.appspot.com',
  );

}